language: python
os: linux
dist: focal
python:
  - "3.7"

addons:
  apt:
    update: true
    packages: 
      - texlive
      - texlive-fonts-recommended
      - texlive-latex-extra
      - texlive-science
      - latexmk

install:
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  - conda env create -n book -f environment.yml
  - conda init zsh
  - source /home/travis/miniconda/etc/profile.d/conda.sh
  - conda activate book
  - pip install -U jupyter-book
  - pip install pyppeteer
  - python -c 'import pyppeteer; pyppeteer.chromium_downloader.download_chromium()'


script:
  - jupyter-book build lecture --builder pdflatex
  - jupyter nbconvert ML4NeutronImageSegmentation.ipynb --to slides --execute --output-dir='./docs'


#deploy:
#  provider: releases
#  github_token: $GITHUB_TOKEN
#  file: "lecture/_build/latex/MLSegmentation4NI.pdf"
#  skip_cleanup: true
#  draft: true
#  on:
#     branch: main

deploy:
   provider: pages
   skip_cleanup: true
   github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
   keep_history: true
   file: "lecture/_build/latex/MLSegmentation4NI.pdf"
   target_branch: gh-pages
   on:
     branch: main
